[template]
src   = "keystone-paste.ini"
dest  = "/etc/keystone/keystone-paste.ini"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/openstack/keystone",
  "/openstack/database",
]
check_cmd = "/app/bin/check {{ .src }}"
